#!/bin/bash

#set global variables
s3_archive_path=s3://roames-weathervis/archive/
ftp_path=/WeatherShare/ftp-archive/
process_path=/WeatherShare/procd-archive/
last_day=$(date +"%u") #day of week 1-7

max_archive_days="+7"

touch clean_ftp_process_kill_flag

while [ -f clean_ftp_process_kill_flag ]          #check if archive kill flag still exists
do
	#get current day number
	current_day=$(date +"%u")
	
	#if at new day
	if [ "$current_day" -ne "$last_day" ]; then
		echo "NEW-DAY ARCHIVING TRIGGER"
		#delete ftp data at subdir level 3
		echo "Removing old ftp data"
		find $ftp_path -maxdepth 3 -mindepth 3 -type d -mtime $max_archive_days -exec rm -Rf {} \;
		#find $ftp_path -maxdepth 3 -mindepth 3 -type d -mtime $max_archive_days -exec s3cmd sync --skip-existing /WeatherShare/ftp-archive/2013/7/31 $s3_archive_path \;

		#delete process data at subdir level 4
		echo "Remove old process data"
		find $process_path -maxdepth 4 -mindepth 4 -type d -mtime $max_archive_days -exec rm -Rf {} \;
		last_day=$current_day
	fi

	echo "SLEEPING for 10min"
	sleep 600
done
