function kml_str=ge_balloon_graph_style(kml_str,Style_id)
%style for balloon storm history graph containing html template and icon link

out=['<Style id="',Style_id,'">',10,...
        '<BalloonStyle>',10,...
            '<text><![CDATA[',...
                '<img src="http://chart.apis.google.com/chart?&chxt=x,y&chs=150x100&cht=lxy&chds=a&chd=t:$[x_data1]|$[y_data1]&chco=FF0000&chls=1,6,3&chtt=$[ctitle1]"/>',...
                '<img src="http://chart.apis.google.com/chart?&chxt=x,y&chs=150x100&cht=lxy&chds=a&chd=t:$[x_data2]|$[y_data2]&chco=0000FF&chls=1,6,3&chtt=$[ctitle2]"/>',...
                '<img src="http://chart.apis.google.com/chart?&chxt=x,y&chs=150x100&cht=lxy&chds=a&chd=t:$[x_data3]|$[y_data3]&chco=00FF00&chls=1,6,3&chtt=$[ctitle3]"/>',...
            ']]></text>',10,...
       '</BalloonStyle>',10,...
       '<IconStyle>',10,...
			'<Icon>',10,...
				'<href>https://cdn0.iconfinder.com/data/icons/free-misc-icon-set-2/512/graph_up_arrow-128.png</href>',10,...
			'</Icon>',10,...
		'</IconStyle>',10,...
        '<LabelStyle>',10,...
            '<scale>0</scale>',10,...
        '</LabelStyle>',10,...    
    '</Style>',10];

kml_str=[kml_str,out];
