function kml_str=ge_balloon_stats_style(kml_str,Style_id)
%WHAT: Generates the style kml for the storm stats ballon with the extended
%data template and the icon http link

out=['<Style id="',Style_id,'">',10,...
        '<BalloonStyle>',10,...
            '<text>',10,...
                 '<![CDATA[',10,...
                     '<b><font face="Courier">VILD: $[VILD] g/m^3</font></b><br/>',10,...
                     '<br/>',10,...
                     '<b><font face="Courier">MESH: $[MESH] mm</font></b><br/>',10,...
                     '<br/>',10,...
                     '<b><font face="Courier">Tops: $[EchoTopH] km</font></b><br/>',10,...
                     '<br/>',10,...
                     '<b><font face="Courier">Ctag: $[storm_id]</font></b><br/>',10,...
                     '<br/>',10,...
                 ']]>',10,...
                 '$[geDirections]',10,...
            '</text>',10,...
       '</BalloonStyle>',10,...
       '<IconStyle>',10,...
			'<Icon>',10,...
				'<href>http://www.myiconfinder.com/uploads/iconsets/256-256-bcfd5fd1da3195cb34be5b122393d83d-thunder.png</href>',10,...
			'</Icon>',10,...
		'</IconStyle>',10,...
        '<LabelStyle>',10,...
            '<scale>0</scale>',10,...
        '</LabelStyle>',10,...    
    '</Style>',10];

kml_str=[kml_str,out];