function kml_str=ge_balloon_stats_placemark(kml_str,vis,Style_id,place_id,vild,mesh,tops,storm_id,lat,lon,timeSpanStart,timeSpanStop)
%WHAT: generates kml for the storm stats values (3) using extendeddata as inputs
%(template stored in style). anchored at lat lon at a height of 20km


%build timekml if values inputted, otherwise blank
if isempty(timeSpanStart)
    timekml='';
else
    timekml=['<TimeSpan><begin>' timeSpanStart '</begin><end>' timeSpanStop '</end></TimeSpan>',10];
end


out=['<Placemark>',10,...
            '<name>',place_id,'</name>',10,...
            '<styleUrl>',Style_id,'</styleUrl>',10,...
            '<visibility>',num2str(vis),'</visibility>',10,...
            timekml,...
            '<ExtendedData>',10,...
                '<Data name="VILD">',10,...
                    '<value>',num2str(vild),'</value>',10,...
                '</Data>',10,...
                '<Data name="MESH">',10,...
                    '<value>',num2str(mesh),'</value>',10,...
                '</Data>',10,...
                '<Data name="EchoTopH">',10,...
                    '<value>',num2str(tops),'</value>',10,...
                '</Data>',10,...
                '<Data name="storm_id">',10,...
                    '<value>',storm_id,'</value>',10,...
                '</Data>',10,...
            '</ExtendedData>',10,...
            '<Point>',10,...
                '<extrude>1</extrude>',10,...
                '<altitudeMode>absolute</altitudeMode>',10,...
                '<coordinates>',num2str(lon),',',num2str(lat),',',num2str(20000),'</coordinates>',10,...
            '</Point>',10,...
    '</Placemark>',10];
    
kml_str=[kml_str,out];