function kml_folders_str=ge_folder(kml_folders_str,kml_places_str,name,description,visible)
%WHAT: wraps the input kml in a folder with name, description and
%visibility

out=        ['<Folder>',10,...
                    '<name>',name,'</name>',10,...
                    '<visibility>',num2str(visible),'</visibility>',10,... 
                    '<description>',description,'</description>',10,...
                    kml_places_str,...
             '</Folder>',10];
         
kml_folders_str=[kml_folders_str,out];        
         
         