function kml_str=ge_groundoverlay_gx(kml_str,name,image_path,latlonquad,timeSpanStart,timeSpanStop,altitudemode,altitude,visible)
%WHAT: generates a ground overlay kml object for an image using its latlonbox,
%start/stop ts
latlonquad_str = sprintf('%f,%f %f,%f %f,%f %f,%f',latlonquad);
%build altitudemode kml string
if strcmp(altitudemode,'clamped')
    altkml=['<altitudeMode>clampToGround</altitudeMode>',10];
elseif strcmp(altitudemode,'absolute')
    altkml=['<altitudeMode>absolute</altitudeMode>',10,...
        '<altitude>',num2str(altitude),'</altitude>',10];
end

%build timekml if values inputted, otherwise blank
if isempty(timeSpanStart)
    timekml='';
else
    timekml=['<TimeSpan><begin>' timeSpanStart '</begin><end>' timeSpanStop '</end></TimeSpan>',10];
end

out=['<GroundOverlay>',10,...
        '<name>',name,'</name>',10,...
        '<visibility>',num2str(visible),'</visibility>',10,...   
        timekml,...
        '<color>C0ffffff</color>',10,...
        '<Icon>',...
             '<href>',image_path,'</href>',10,...
        '</Icon>',10,...
        altkml,...
        '<gx:LatLonQuad>',10,...
            '<coordinates>',10,...
                latlonquad_str,10,...
            '</coordinates>',10,...    
        '</gx:LatLonQuad>',10,...
      '</GroundOverlay>',10];
  
kml_str=[kml_str,out]; 
             
