function kml_str=ge_line_style(kml_str,Style_id,LineColor,LineWidth)
%WHAT: Generates a line style (colour and width) kml string

out=['<Style id="',Style_id,'">',10,...
        '<LineStyle>',10,...
            '<width>',num2str(LineWidth),'</width>',10,...
            '<color>',LineColor,'</color>',10,...
        '</LineStyle>',10,...
    '</Style>',10];

kml_str=[kml_str,out];