function kml_str=ge_model(kml_str,vis,link,model_id,lat,lon,timeSpanStart,timeSpanStop)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Joshua Soderholm, Fugro ROAMES, 2017
%
% WHAT: wraps a collada model in kml
% INPUTS
% kml_str: string containing kml
% vis: flag for visbility (binary)
% link: link to collada file (can be relative)
% model_id: name for kml object (String)
% lat: lat value for model centroid? placement (number) (deg)
% lon: lon value for model centroid? placement (number) (deg)
% timeSpanStart: starting time for kml time span (GE timestamp) (str)
% timeSpanStop: stoping time for kml time span (GE timestamp) (str)
% RETURNS
% kml_str: string containing kml
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%build timekml if values inputted, otherwise blank
if isempty(timeSpanStart)
    timekml='';
else
    timekml=['<TimeSpan><begin>' timeSpanStart '</begin><end>' timeSpanStop '</end></TimeSpan>',10];
end


out=['<Placemark>',10,...
            '<name>',model_id,'</name>',10,...
            '<visibility>',num2str(vis),'</visibility>',10,...
            timekml,...
            '<Model>',10,...
                '<altitudeMode>clampToGround</altitudeMode>',10,...
                '<Location>',10,...
                    '<longitude>',num2str(lon),'</longitude>',10,...
                    '<latitude>',num2str(lat),'</latitude>',10,...
                    '<altitude>',num2str(0),'</altitude>',10,...
                '</Location>',10,...
                '<Link>',...
                    '<href>',link,'</href>',10,...
                    '<refreshMode>onChange</refreshMode>',10,...
                '</Link>',10,...
                '<Orientation>',10,...
                    '<heading>0.0</heading>',10,...
                    '<tilt>0.0</tilt>',10,...
                    '<roll>0.0</roll>',10,...
                 '</Orientation>',10,...
                 '<Scale>',10,...
                    '<x>1.0</x>',10,...
                    '<y>1.0</y>',10,...
                    '<z>1.0</z>',10,...
                 '</Scale>',10,...
            '</Model>',10,...
    '</Placemark>',10];
    
kml_str=[kml_str,out];
