function kml_str=ge_nowcast_placemark(kml_str,vis,Style_id,place_id,x_data,table_html,y_data1,ctitle1,y_data2,ctitle2,y_data3,ctitle3,lat,lon)
%WHAT: creates a balloon placemark showing 3 graphs generated using the
%google image charts html service. html structure is stored in the style
%for this object and inputs are passed as extended objects. anchored at lat
%lon at a height of 20km


%write matrices to text format for 3 datasets
x_data=sprintf('%4.2f,',x_data); x_data=x_data(1:end-1);
y_data1=sprintf('%4.2f,',y_data1); y_data1=y_data1(1:end-1);
y_data2=sprintf('%4.2f,',y_data2); y_data2=y_data2(1:end-1);
y_data3=sprintf('%4.2f,',y_data3); y_data3=y_data3(1:end-1);

%build kml extended data entries
out=['<Placemark>',10,...
            '<name>',place_id,'</name>',10,...
            '<styleUrl>',Style_id,'</styleUrl>',10,...
            '<visibility>',num2str(vis),'</visibility>',10,...  
            '<ExtendedData>',10,...
                '<Data name="table_html">',10,...
                    '<value>',table_html,'</value>',10,...
                '</Data>',10,...
                '<Data name="x_data1">',10,...
                    '<value>',x_data,'</value>',10,...
                '</Data>',10,...
                '<Data name="y_data1">',10,...
                    '<value>',y_data1,'</value>',10,...
                '</Data>',10,...
                '<Data name="ctitle1">',10,...
                    '<value>',ctitle1,'</value>',10,...
                '</Data>',10,...
                '<Data name="x_data2">',10,...
                    '<value>',x_data,'</value>',10,...
                '</Data>',10,...
                '<Data name="y_data2">',10,...
                    '<value>',y_data2,'</value>',10,...
                '</Data>',10,...
                '<Data name="ctitle2">',10,...
                    '<value>',ctitle2,'</value>',10,...
                '</Data>',10,...
                '<Data name="x_data3">',10,...
                    '<value>',x_data,'</value>',10,...
                '</Data>',10,...
                '<Data name="y_data3">',10,...
                    '<value>',y_data3,'</value>',10,...
                '</Data>',10,...
                '<Data name="ctitle3">',10,...
                    '<value>',ctitle3,'</value>',10,...
                '</Data>',10,...
            '</ExtendedData>',10,...
            '<Point>',10,...
                '<extrude>1</extrude>',10,...
                '<altitudeMode>absolute</altitudeMode>',10,...
                '<coordinates>',num2str(lon),',',num2str(lat),',',num2str(20000),'</coordinates>',10,...
            '</Point>',10,...
    '</Placemark>',10];

%cat to input kml string
kml_str=[kml_str,out];