function kml_str=ge_nowcast_multipoly_style(kml_str,Style_id,LineColor,LineWidth,PolyColor)
%WHAT: Create a polygon style kml file using line colour, poly colour and
%line width

if isempty(LineColor)
    LineColor=PolyColor;
end
    
out=['<Style id="',Style_id,'">',10,...
       '<BalloonStyle>',10,...
            '<text><![CDATA[',...
                '$[description]<br/>',...
                '<img src="http://chart.apis.google.com/chart?&chxt=x,y&chs=150x100&cht=lxy&chds=a&chd=t:$[x_data1]|$[y_data1]&chco=FF0000&chls=1,6,3&chtt=$[ctitle1]"/>',...
                '<img src="http://chart.apis.google.com/chart?&chxt=x,y&chs=150x100&cht=lxy&chds=a&chd=t:$[x_data2]|$[y_data2]&chco=0000FF&chls=1,6,3&chtt=$[ctitle2]"/>',...
                '<img src="http://chart.apis.google.com/chart?&chxt=x,y&chs=150x100&cht=lxy&chds=a&chd=t:$[x_data3]|$[y_data3]&chco=00FF00&chls=1,6,3&chtt=$[ctitle3]"/>',...
            ']]></text>',10,...
       '</BalloonStyle>',10,...
        '<LineStyle>',10,...
            '<width>',num2str(LineWidth),'</width>',10,...
            '<color>',LineColor,'</color>',10,...
        '</LineStyle>',10,...
        '<PolyStyle>',10,...
            '<color>',PolyColor,'</color>',10,...
        '</PolyStyle>',10,...
    '</Style>',10];

kml_str=[kml_str,out];