function kml_str=ge_networklink(kml_str,name,Link,flyToView,refreshVisibility,refreshtime,region,timeSpanStart,timeSpanStop,visible)
%Generates a network link kml string for a kml/kmz file.

if isempty(timeSpanStart)
    timekml='';
else
    timekml=['<TimeSpan><begin>' timeSpanStart '</begin><end>' timeSpanStop '</end></TimeSpan>',10];
end

if isempty(refreshtime)
    refresh_kml='';
else
    refresh_kml=['<refreshMode>onInterval</refreshMode><refreshInterval>',num2str(refreshtime),'</refreshInterval>',10];
end

out='';

out=['<NetworkLink>',10,...
        '<name>',name,'</name>',10,...
        '<visibility>',num2str(visible),'</visibility>',10,...   
        region,...
        timekml,...
        '<refreshVisibility>',num2str(refreshVisibility),'</refreshVisibility>',10,...
        '<flyToView>',num2str(flyToView),'</flyToView>',10,...
        '<Link>',10,...
            '<href>',Link,'</href>',10,...
            refresh_kml,...
        '</Link>',10,...
     '</NetworkLink>',10];
    
kml_str=[out,kml_str];
    