function kml_str=ge_point_placemark_style(kml_str,Style_id)
%WHAT: Generates the style kml for the storm stats ballon with the extended
%data template and the icon http link

out=['<Style id="',Style_id,'">',10,...
       '<IconStyle>',10,...
            '<scale>.5</scale>',10,...
			'<Icon>',10,...
				'<href>http://maps.google.com/mapfiles/kml/shapes/open-diamond.png</href>',10,...
			'</Icon>',10,...
		'</IconStyle>',10,...
        '<LabelStyle>',10,...
            '<scale>0</scale>',10,...
        '</LabelStyle>',10,...
    '</Style>',10];

kml_str=[kml_str,out];
