function kml_str=ge_point_placemark(kml_str,vis,Style_id,place_id,lat,lon)
%WHAT: generates kml for the storm stats values (3) using extendeddata as inputs
%(template stored in style). anchored at lat lon at a height of 20km

out=['<Placemark>',10,...
            '<name>',place_id,'</name>',10,...
            '<styleUrl>',Style_id,'</styleUrl>',10,...
            '<visibility>',num2str(vis),'</visibility>',10,...  
            '<Point>',10,...
                '<extrude>0</extrude>',10,...
                '<altitudeMode>clampToGround</altitudeMode>',10,...
                '<coordinates>',num2str(lon),',',num2str(lat),',',num2str(0),'</coordinates>',10,...
            '</Point>',10,...
    '</Placemark>',10];
    
kml_str=[kml_str,out];