function out=ge_region(latlonbox,minAlt,maxAlt,minLod,maxLod)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Joshua Soderholm, Fugro ROAMES, 2017
%
% WHAT: generates a kml string latlonaltbox and LoD info
% INPUTS
% latlonbox: 4 element matrix containing [N,S,E,W] (matrix)
% minAlt: min altitude for visbility (number) (m)
% maxAlt: max altitude for visbility (number) (m) 
% minLod: min lod for visbility (number) (pixels)
% maxLod: max lod for visbility (number) (pixels) 
% RETURNS
% out: string containing region kml
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

out=['<Region> ',10,...
        '<LatLonAltBox>',10,...
            '<north>',num2str(latlonbox(1)),'</north>',10,...
            '<south>',num2str(latlonbox(2)),'</south>',10,...
            '<east>',num2str(latlonbox(3)),'</east>',10,...
            '<west>',num2str(latlonbox(4)),'</west>',10,...
            '<minAltitude>',num2str(minAlt),'</minAltitude>',10,... 
            '<maxAltitude>',num2str(maxAlt),'</maxAltitude>',10,...  
       '</LatLonAltBox>',10,... 
       '<Lod>',10,...
            '<minLodPixels>',num2str(minLod),'</minLodPixels>',10,... 
            '<maxLodPixels>',num2str(maxLod),'</maxLodPixels>',10,... 
       '</Lod>',10,...
    '</Region>',10];

