function out=ge_region(latlonbox,minAlt,maxAlt,minLod,maxLod)
%WHAT: generates a kml string latlonaltbox and LoD info


out=['<Region> ',10,...
        '<LatLonAltBox>',10,...
            '<north>',num2str(latlonbox(1)),'</north>',10,...
            '<south>',num2str(latlonbox(2)),'</south>',10,...
            '<east>',num2str(latlonbox(3)),'</east>',10,...
            '<west>',num2str(latlonbox(4)),'</west>',10,...
            '<minAltitude>',num2str(minAlt),'</minAltitude>',10,... 
            '<maxAltitude>',num2str(maxAlt),'</maxAltitude>',10,...  
       '</LatLonAltBox>',10,... 
       '<Lod>',10,...
            '<minLodPixels>',num2str(minLod),'</minLodPixels>',10,... 
            '<maxLodPixels>',num2str(maxLod),'</maxLodPixels>',10,... 
       '</Lod>',10,...
    '</Region>',10];

