function kml_str=ge_swath_placemark(kml_str,vis,Style_id,place_id,table_html,lat,lon,height)
%WHAT: creates a balloon placemark showing a html table for a swath polygon
%object. This table typically contains information on asset impact

%build kml extended data entries
out=['<Placemark>',10,...
            '<name>',place_id,'</name>',10,...
            '<styleUrl>',Style_id,'</styleUrl>',10,...
            '<visibility>',num2str(vis),'</visibility>',10,...  
            '<ExtendedData>',10,...
                '<Data name="table_html">',10,...
                    '<value>',table_html,'</value>',10,...
                '</Data>',10,...
            '</ExtendedData>',10,...
            '<Point>',10,...
                '<extrude>1</extrude>',10,...
                '<altitudeMode>absolute</altitudeMode>',10,...
                '<coordinates>',num2str(lon),',',num2str(lat),',',num2str(height),'</coordinates>',10,...
            '</Point>',10,...
    '</Placemark>',10];

%cat to input kml string
kml_str=[kml_str,out];