function kml_str=ge_swath_poly_style(kml_str,Style_id,LineColor,LineWidth,PolyColor)
%WHAT: Create a polygon style kml file using line colour, poly colour and
%line width

if isempty(LineColor)
    LineColor=PolyColor;
end
    
out=['<Style id="',Style_id,'">',10,...
       '<BalloonStyle>',10,...
            '<text><![CDATA[',...
                '$[description]<br/>',...
            ']]></text>',10,...
       '</BalloonStyle>',10,...
        '<LineStyle>',10,...
            '<width>',num2str(LineWidth),'</width>',10,...
            '<color>',LineColor,'</color>',10,...
        '</LineStyle>',10,...
        '<PolyStyle>',10,...
            '<color>',PolyColor,'</color>',10,...
        '</PolyStyle>',10,...
    '</Style>',10];

kml_str=[kml_str,out];