function kml_str=ge_swath_placemark_style(kml_str,Style_id,url_prefix,icons_path,icon_color)
%style for balloon storm history graph containing html template and icon link

out=['<Style id="',Style_id,'">',10,...
        '<BalloonStyle>',10,...
            '<text><![CDATA[',...
                '$[table_html]<br/>',...
            ']]></text>',10,...
       '</BalloonStyle>',10,...
       '<LineStyle>',10,...
		    '<color>',icon_color,'</color>',10,...
	   '</LineStyle>',10,...
       '<IconStyle>',10,...
            '<color>',icon_color,'</color>',10,...
			'<Icon>',10,...
				'<href>',[url_prefix,icons_path,'house_icon.png'],'</href>',10,...
			'</Icon>',10,...
		'</IconStyle>',10,...
        '<LabelStyle>',10,...
            '<scale>0</scale>',10,...
        '</LabelStyle>',10,...    
    '</Style>',10];

kml_str=[kml_str,out];
